language: node_js

node_js:
  - "11.1.0"
services:
  - mongodb
env:
  - MONGO_DB="mongodb://localhost/tempjs"
before_script:
  - sleep 15

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
    node_js: 11.1.0
